version: 2

references:

    docker-python36: &docker-python36
        docker:
            - image: circleci/python:3.6.5
              environment:
                PY: 36

    docker-python37: &docker-python37
        docker:
            - image: circleci/python:3.7
              environment:
                PY: 37

    docker-python27: &docker-python27
        docker:
            - image: circleci/python:2.7.14
              environment:
                PY: 27
                REQUIREMENTS: -rpy2-dev-requirements.txt


    workspace: &workspace
        attach_workspace:
            at: .

    cache-python-36: &cache-python-36
        key: py36-deps-{{ arch }}-{{ checksum "workspace/.py-cache" }}

    cache-python-36: &cache-python-37
        key: py37-deps-{{ arch }}-{{ checksum "workspace/.py-cache" }}

    cache-python-27: &cache-python-27
        key: py27-deps-{{ arch }}-{{ checksum "workspace/.py-cache" }}

    deps: &deps
        run:
            name: Installing dependencies
            command: |
                mkdir -p ~/.cache/pip
                virtualenv --clear --python $(which python) "venv${PY}"
                tar -C workspace -cpf - src | tar -C "venv${PY}" -xpf -
                . "venv${PY}/bin/activate" && cd "venv${PY}/src"
                pip install ${REQUIREMENTS:-'-rdev-requirements.txt'}

    run-tests: &run-tests
        run:
            name: Run tests
            command: |
                . "venv${PY}/bin/activate" && cd "venv${PY}/src"
                inv test --coverage --junit --no-bail

    mv-tests: &mv-tests
        run:
            name: Format and move test results
            when: always
            command: |
                results="$(pwd)/workspace/test-results"
                checkout="$(pwd)/workspace/src"
                mkdir -p "${results}/python${PY}"
                . "venv${PY}/bin/activate" && cd "venv${PY}/src"
                python -c \
                    'import sys; sys.stdout.write(sys.stdin.read().replace(sys.argv[1], sys.argv[2]))' \
                    "$(pwd)/" "${checkout}/" < .coverage >"${results}/python${PY}/.coverage" || true
                mv coverage.xml ${results}/python${PY}/results.xml || true
                mv junit.xml "${results}/python${PY}/junit.xml" || true
                mv htmlcov ${results}/python${PY} || true

    store-tests: &store-tests
        store_test_results:
            path: workspace/test-results

jobs:
    checkout:
        <<: *docker-python36
        steps:
            - run:
                name: Prepare working directory
                command: mkdir -p workspace/src
            - checkout: {path: workspace/src}
            - run:
                name: Creating cachekey(s)
                command: |
                    cd workspace
                    echo 1 >.py-cache
                    cat src/dev-requirements*.txt >> .py-cache
                    cat src/setup.py >> .py-cache
            - persist_to_workspace:
                paths: workspace
                root: .

    deps-36:
        <<: *docker-python36
        steps:
            - *workspace
            - restore_cache: *cache-python-36
            - *deps
            - save_cache:
                <<: *cache-python-36
                paths: ~/.cache/pip
            - persist_to_workspace:
                paths: venv36
                root: .

    deps-27:
        <<: *docker-python27
        steps:
            - *workspace
            - restore_cache: *cache-python-27
            - *deps
            - save_cache:
                <<: *cache-python-27
                paths: ~/.cache/pip
            - persist_to_workspace:
                paths: venv27
                root: .

    deps-37:
        <<: *docker-python37
        steps:
            - *workspace
            - restore_cache: *cache-python-37
            - *deps
            - save_cache:
                <<: *cache-python-37
                paths: ~/.cache/pip
            - persist_to_workspace:
                paths: venv37
                root: .

    test-36:
        <<: *docker-python36
        steps:
            - *workspace
            - restore_cache: *cache-python-36
            - *run-tests
            - *mv-tests
            - *store-tests
            - persist_to_workspace:
                paths: workspace/test-results/python36
                root: .

    test-27:
        <<: *docker-python27
        steps:
            - *workspace
            - restore_cache: *cache-python-27
            - *run-tests
            - *mv-tests
            - *store-tests
            - persist_to_workspace:
                paths: workspace/test-results/python27
                root: .

    test-37:
        <<: *docker-python37
        steps:
            - *workspace
            - restore_cache: *cache-python-37
            - *run-tests
            - *mv-tests
            - *store-tests
            - persist_to_workspace:
                paths: workspace/test-results/python37
                root: .

    collect-tests:
        <<: *docker-python36
        steps:
            - *workspace
            - run:
                name: Collect test results across Python versions
                command: |
                    results="$(pwd)/workspace/test-results"
                    . "venv${PY}/bin/activate" && cd workspace/src
                    mkdir -p "${results}/python"
                    ls -1 "${results}" | grep python. | while read file; do
                        cp "${results}/${file}/.coverage" ".coverage.${file}" || true
                        mv "${results}/${file}/results.xml" "${results}/${file}.xml" || true
                        mv "${results}/${file}/junit.xml" "${results}/${file}.junit.xml" || true
                        mv "${results}/${file}" "${results}/python/${file##python}"
                    done
                    if [ -n "$(ls -1 .coverage.* 2>/dev/null || true)" ]; then
                        which coverage >/dev/null 2>&1 || pip install coverage
                        coverage erase
                        coverage combine
                        coverage report --rcfile pytest.ini
                        coverage html --rcfile pytest.ini
                        coverage xml --rcfile pytest.ini
                        mv .coverage coverage.xml htmlcov/* ${results}/python/
                    fi
            - *store-tests
            - store_artifacts: {path: workspace/test-results, destination: .}

    lint:
        <<: *docker-python36
        steps:
            - *workspace
            - restore_cache: *cache-python-36
            - run:
                name: Running linter(s)
                command: |
                    . "venv${PY}/bin/activate" && cd "venv${PY}/src"
                    inv lint

    docs:
        <<: *docker-python36
        steps:
            - *workspace
            - restore_cache: *cache-python-36
            - run:
                name: Generating documentation
                command: |
                    mkdir -p "$(pwd)/workspace/docs/"
                    results="$(pwd)/workspace/docs"
                    . "venv${PY}/bin/activate" && cd "venv${PY}/src"
                    inv docs --strict
                    mv docs/_build/* "${results}"
            - store_artifacts: {path: workspace/docs, destination: .}

workflows:
  version: 2

  build:
    jobs:
        - checkout
        - deps-36:
            requires:
                - checkout
        - lint:
            requires:
                - deps-36
        - test-36:
            requires:
                - deps-36
        - deps-27:
            requires:
                - checkout
        - test-27:
            requires:
                - deps-27
        - deps-37:
            requires:
                - checkout
        - test-37:
            requires:
                - deps-37
        - collect-tests:
            requires:
                - test-36
                - test-27
                - test-37
        - docs:
            requires:
                - test-36
                - test-27
                - test-37
                - lint


