name: ci

on:
  - push
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python: ["3.5", "3.6", "3.7", "3.8"]
        include:
          - python: "3.5"
            docker-image: "python:3.5-buster"
          - python: "3.6"
            docker-image: "python:3.6-buster"
          - python: "3.7"
            docker-image: "python:3.7-buster"
          - python: "3.8"
            docker-image: "python:3.8-buster"

    container:
      image: ${{ matrix.docker-image }}

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Dependencies
        run: |
          mkdir -p .pip-cache
          pip install --cache-dir .pip-cache --upgrade -r dev-requirements.txt
          python setup.py develop

      - name: (Debug) dependency versions
        run: |
          python --version
          pip --version
          pip freeze

      - name: Check formatting
        if: matrix.python != '3.5'
        run: |
          inv black --check

      - name: Lint (Flake 8)
        run: |
          inv flake8 --junit

      - name: Lint (Mypy)
        run: |
          inv mypy --junit

      - name: Test & Coverage
        run: |
          inv test -v --coverage --junit --no-bail

      - name: Check benchmarks run
        run: |
          inv benchmark

      - name: Test with Cython
        run: |
          pip install --cache-dir .pip-cache cython
          pip install -v -e .
          PY_IGNORE_IMPORTMISMATCH=1 inv test -v --no-bail
          inv clean

      - name: Build docs
        run: |
          inv docs
