name: ci

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.5", "3.6", "3.7"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Dependencies
        run: |
          pip install -v --upgrade -r dev-requirements.txt -e .
          pip freeze

      - name: Check formatting
        if: matrix.python == '3.7'
        run: |
          inv black --check

      - name: Lint (Flake 8)
        run: |
          inv flake8 --junit

      - name: Lint (Mypy)
        run: |
          inv mypy --junit

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.5", "3.6", "3.7"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Dependencies
        run: |
          pip install -v --upgrade -r test-requirements.txt -e .
          pip freeze

      - name: Test & Coverage
        run: |
          inv test -v --coverage --junit --no-bail

      - name: Check benchmarks run
        if: matrix.python == '3.7'
        run: |
          inv benchmark

  test-cython:
    runs-on: ubuntu-latest

    needs: [test]

    strategy:
      matrix:
        python: ["3.6", "3.7"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Dependencies
        run: |
          pip install cython
          pip install -v --upgrade -r test-requirements.txt -e .
          pip freeze

      - name: Test
        run: |
          inv test -v --junit --no-bail
