name: ci

on:
  - push

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.5"
          - "3.6"
          - "3.7"
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Dependencies
        run: |
          pip install -r dev-requirements.txt
