name: ci

on:
  - push

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.5"
          - "3.6"
          - "3.7"

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Dependencies
        run: |
          pip install --upgrade -r dev-requirements.txt -e .

      - name: Lint (Flake 8)
        run: |
          inv flake8 --junit

      - name: Lint (Mypy)
        run: |
          inv mypy --junit

      - name: Test & Coverage
        run: |
          inv test -v --coverage --junit --no-bail
