name: ci

on:
  - push
  - pull_request

jobs:
  check:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python: [3.5, 3.6, 3.7, 3.8, pypy3]
        os: [ubuntu-latest, macos-latest]
        exclude:
          # Testing on macos mostly to make sure dev doesn't break.
          - os: macos-latest
            python: 3.5
          - os: macos-latest
            python: 3.6
          - os: macos-latest
            python: 3.7
          - os: macos-latest
            python: pypy3

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Cache deps
        uses: actions/cache@v1
        with:
          path: .pip-cache
          key: ${{ runner.os }}-python-${{ matrix.python }}-${{ hashFiles('*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ matrix.python }}-
            ${{ runner.os }}-python-
            ${{ runner.os }}-

      - name: Dependencies
        if: matrix.python != 'pypy3'
        run: |
          mkdir -p .pip-cache
          pip install --cache-dir .pip-cache --upgrade -r dev-requirements.txt
          python setup.py develop

      # Some dev dependencies don't build under pypy but testing deps and py-gql
      # should work.
      - name: Dependencies (PyPy)
        if: matrix.python == 'pypy3'
        run: |
          mkdir -p .pip-cache
          pip install --cache-dir .pip-cache --upgrade -r test-requirements.txt
          python setup.py develop

      - name: (Debug) dependency versions
        run: |
          python --version
          pip --version
          pip freeze

      - name: Check formatting
        if: matrix.python != '3.5' && matrix.python != 'pypy3'
        run: |
          inv black --check

      - name: Lint (Flake 8)
        if: matrix.python != 'pypy3'
        run: |
          inv flake8 --junit

      - name: Lint (Mypy)
        if: matrix.python != 'pypy3'
        run: |
          inv mypy --junit

      - name: Test & Coverage
        if: matrix.python != 'pypy3'
        run: |
          inv test -v --coverage --junit --no-bail

      - name: Test - No Coverage
        if: matrix.python == 'pypy3'
        run: |
          inv test -v --junit --no-bail

      - name: Check benchmarks run
        if: matrix.python != 'pypy3'
        run: |
          inv benchmark

      - name: Test with Cython
        if: matrix.python != 'pypy3'
        run: |
          PY_GQL_USE_CYTHON=1 python setup.py develop
          PY_IGNORE_IMPORTMISMATCH=1 inv test -v --no-bail
          inv clean --cython

      - name: Build docs
        if: matrix.python == '3.8'
        run: |
          inv docs

      - uses: codecov/codecov-action@v1
        if: matrix.python != 'pypy3'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest

    needs:
      - check

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Cache deps
        uses: actions/cache@v1
        with:
          path: .pip-cache
          key: ${{ runner.os }}-python-build-deps

      - name: Dependencies
        run: |
          mkdir -p .pip-cache
          pip install --cache-dir .pip-cache --upgrade pip wheel setuptools 'cython<3' 'invoke~=1.1'

      - name: Build base wheel and source distribution
        run: inv build

      # manylinux wheels are not used in releases yet
      # - name: Build manylinux wheels
      #   run: inv build-manylinux-wheels --cythonize-module --python 3.8

      - name: Generate checksums
        run: |
          cd dist
          find . -name "*py_gql*"" -type f -exec sha256sum "{}" + > checksum.txt
          cd ..

      - name: Upload dist
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
