name: ci

on:
  - push
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python: ["3.5", "3.6", "3.7", "3.8-rc"]

    container:
      image: python:${{ matrix.python }}-buster

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Dependencies
        run: |
          pip install --upgrade -r dev-requirements.txt
          python setup.py develop

      - name: (Debug) dependency versions
        run: |
          python --version
          pip --version
          pip freeze

      - name: Check formatting
        if: matrix.python == '3.7'
        run: |
          inv black --check

      - name: Lint (Flake 8)
        run: |
          inv flake8 --junit

      - name: Lint (Mypy)
        run: |
          inv mypy --junit

      - name: Test & Coverage
        run: |
          inv test -v --coverage --junit --no-bail

      - name: Check benchmarks run
        if: matrix.python == '3.7'
        run: |
          inv benchmark

      - name: Test with Cython
        if: matrix.python != '3.8-rc'
        run: |
          pip install cython
          pip install -v -e .
          PY_IGNORE_IMPORTMISMATCH=1 inv test -v --no-bail
          inv clean

      - name: Build docs
        if: matrix.python == '3.7'
        run: |
          inv docs -s
