name: ci

on:
  - push
  - pull_request

jobs:
  check:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python: [3.5, 3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Dependencies
        run: |
          mkdir -p .pip-cache
          pip install --cache-dir .pip-cache --upgrade -r dev-requirements.txt
          python setup.py develop

      - name: (Debug) dependency versions
        run: |
          python --version
          pip --version
          pip freeze

      - name: Check formatting
        if: matrix.python != '3.5'
        run: |
          inv black --check

      - name: Lint (Flake 8)
        run: |
          inv flake8 --junit

      - name: Lint (Mypy)
        run: |
          inv mypy --junit

      - name: Test & Coverage
        run: |
          inv test -v --coverage --junit --no-bail

      - name: Check benchmarks run
        run: |
          inv benchmark

      - name: Test with Cython
        run: |
          pip install --cache-dir .pip-cache cython
          pip install -v -e .
          PY_IGNORE_IMPORTMISMATCH=1 inv test -v --no-bail
          inv clean

      - name: Build docs
        if: matrix.python == '3.8'
        run: |
          inv docs

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
